### PR TITLE
flyway 6.4.2

### PR DESCRIPTION
**Pull request by sullis**

### CODE REVIEW

**Comment by FlorianGWE** [comment]
Missing Flyway version update in example projects flyway-test-samples/flyway-test-samples-parent/pom.xml

**Comment by sullis** [comment]
> Missing Flyway version update in example projects flyway-test-samples/flyway-test-samples-parent/pom.xml

fixed

**Comment by FlorianGWE** [comment]
Merge done manually. Due date for release 1 of June

**Comment by FlorianGWE** [comment]
mnanual merged and version 6.4.0 of flyway-test released

**Pull request closed without merging**
